import os
from globals import data_repo, cell_line_sra_pairs


include: "snakemake_additional_files/readMapping.smk"
# include: "snakemake_additional_files/alignmentQC.smk"
# include: "snakemake_additional_files/variantCalling.smk"


def get_sra_dirs():
    # List directories under "data/samples/"
    return [d for d in os.listdir("data/samples") if os.path.isdir(os.path.join("data/samples", d))]



rule all:
    input:
        #f"{data_repo}/output/{{cell_line}}/postMultiqc_report.html"
        expand(f"{data_repo}/input/{{cell_line}}/sorted_{{SRA}}.bam",
                zip,
                cell_line=[pair[0] for pair in cell_line_sra_pairs],
                SRA = [ pair[1] for pair in cell_line_sra_pairs ])        
                # expand(f"{data_repo}/input/{{cell_line}}/alignmentReports/{{cell_line}}_alignment_metrics.txt", 
        #        zip, 
        #        cell_line=[pair[0] for pair in cell_line_sra_pairs], 
        #        SRA=[pair[1] for pair in cell_line_sra_pairs]),
    log:
        "logs/all_rule_log.txt"
    shell:
        "echo {input} > {log}"

# Takes in the input file, config.yaml. Doesn't do anything with it because it has already been processed into cell)line)sra_pairs. What it does do is retrieve SRA names from cell_line_sra_pairs. 
#1 Gets called first because directories_created.txt is not found
rule retrieveData:
    output:
        temp(f"{data_repo}/temp/{{cell_line}}/{{SRA}}/{{SRA}}.sra")
    shell:
        f"""
        mkdir -p {data_repo}/temp/{{wildcards.cell_line}}/{{wildcards.SRA}}
        prefetch {{wildcards.SRA}} --output-directory {data_repo}/temp/{{wildcards.cell_line}}/{{wildcards.SRA}}
        """


# Gets called third, unpacks and deletes the .sra file into protected gunziped files of split paired-end data
rule unpackData:
    input:
       f"{data_repo}/temp/{{cell_line}}/{{SRA}}/{{SRA}}.sra"
    output:
        temp(f"{data_repo}/temp/{{cell_line}}/{{SRA}}/{{SRA}}_1.fastq.gz"),
        temp(f"{data_repo}/temp/{{cell_line}}/{{SRA}}/{{SRA}}_2.fastq.gz")
    shell:
        f"""
        fastq-dump --split-files --gzip --outdir {data_repo}/temp/{{wildcards.cell_line}}/{{wildcards.SRA}}/ {{input}} 
        """



